name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_PAT }}
          user: fraser-isbester
          plugin_followup_sections: repositories
          repositories: 1000
          repositories_forks: true
          repositories_affiliations: owner, collaborator, organization_member
